wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.10
    start_time: 1681108666.026586
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.8.10
      5: 0.13.5
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.001
seed:
  desc: null
  value: 1234
test_batch_size:
  desc: null
  value: 128
